### ISSUE TITLE
Create prototype framework layout

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#1]
**Problem**
All prototype applications generated by RAP need a shell to place the different components into.

**Solution**
Recreate the shell from the project administration prototype in the latest version of Angular.

**Tasks**

- [ ] find out what the shell should contain
- [ ] create shell

- [ ] all components need to be completed before starting this

**Comment by Michiel-s** [comment]
Implemented using the SAKAI open source default layout, including topbar, sidebar and footer.

This module is located in the `src/app/layout` folder
