### ISSUE TITLE
Bug: Change code to use angular forms for edit view pages

### ISSUE THREAD

**Issue by ManondW99** [AmpersandTarski/prototype-frontend#103]

**Comment by ManondW99** [comment]
Do this change for the following:
- Epic AmpersandTarski/prototype-frontend#65 Person
- Epic AmpersandTarski/prototype#146  Atomic
- Epic AmpersandTarski/prototype#145 Box
- Epic AmpersandTarski/prototype-frontend#42 AmpersandTarski/prototype-frontend#46 Project

**Comment by Michiel-s** [comment]
Done. We use the Angular form controls now.
