### ISSUE TITLE
Bug: the atomic-object can for the "is not univalent" case still add the person multiple times

### ISSUE THREAD

**Issue by ManondW99** [AmpersandTarski/prototype-frontend#122]

**Comment by ManondW99** [comment]
The atomic-object can for the "is not relevant" case add a person multiple times. However, this is not relevant because a person who has been added should not return into the list where other people can be added again.

**Comment by Michiel-s** [comment]
Is this a bug in the current/old prototype version or in the new frontend that is being developed?

Adding an object twice in a field (duplicate tuple in relation) is filtered by the backend. No issue there. Please elaborate a bit more on this issue and give an example of the flow.
