### ISSUE TITLE
Add global error handling

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/prototype-frontend#127]
Please read this article: https://pkief.medium.com/global-error-handling-in-angular-ea395ce174b1

I would like to see such an implementation in our application. Not the spinner part, but the part discussing the generic error handling. It uses the [Angular centralized hook for exception handling](https://angular.io/api/core/ErrorHandler)

**Comment by Michiel-s** [comment]
Hi @LiWeiYeh, during the standup today you mentioned that the article above used Angular Material design and we are not. You asked what to do here.

This issue here is **not** about the exact implementation as provided in the article on stackblitz.

What I would like to add to our frontend is a global error handler implemented using the Angular ErrorHandler provider:
```ts
@NgModule({
  declarations: [],
  imports: [CommonModule],
  providers: [
    {
      // processes all errors
      provide: ErrorHandler,
      useClass: GlobalErrorHandler,
    },
  ],
})
export class CoreModule {} <-- I like the idea to have a CoreModule. I'll include this in Issue #158 
```

The GlobalErrorHandler:
```ts
@Injectable()
export class GlobalErrorHandler implements ErrorHandler {
  constructor(
    private errorDialogService: ErrorDialogService, <-- REPLACE WITH NOTIFICATION CENTER SERVICE (doesn't exist yet)
    private zone: NgZone
  ) {}

  handleError(error: any) {
    // Check if it's an error from an HTTP response
    if (!(error instanceof HttpErrorResponse)) {
      error = error.rejection; // get the error object
    }
    this.zone.run(() =>
      this.errorDialogService.openDialog( <-- REPLACE WITH NOTIFICATION CENTER SERVICE (doesn't exist yet)
        error?.message || 'Undefined client error',
        error?.status
      )
    );

    console.error('Error from global error handler', error);
  }
}
```

By setting this up, we can throw errors in our code and have the GloablErrorHandle handle it. A NotificationCenterService (different issue) is then responsible for the UI.

The article also provides examples to test the error behavior:

For local errors in frontend code, just throw an Error
```
localError() {
  throw Error("The app component has thrown an error!");
}
```

For errors from http requests, using a helper website: https://httpstat.us
```
failingRequest() {
  this.http.get("https://httpstat.us/404?sleep=2000").toPromise();
}
```


No need to use the UI implementation from the article. Only the things mentioned above in my comment.

**Comment by byTinus** [comment]
Just like #202 , use the `MessageService` to display the caught errors
