### ISSUE TITLE
Bug: When an Atomic-object item is removed, it is not visible on the screen

### ISSUE THREAD

**Issue by ManondW99** [AmpersandTarski/prototype-frontend#128]
It seems that this is due to an error in the ```remove()```function within the ```atomic-object.ts``` file.

![Image](https://user-images.githubusercontent.com/25156290/212642451-94aabb6d-6d0e-468a-8330-444a3434e0ef.gif)

**Comment by ManondW99** [comment]
When an Atomic-component item is deleted, it will be removed from the database but is not visible on the screen. The deleted Atomic-component should be visible on the screen when removed from the database.

**Comment by hanjoosten** [comment]
I don't understand this. Why is this a bug? Shouldn't the stuff on the screen be synced with what is in the database? Please help my by describing the context, what happened and what you expected.
