### ISSUE TITLE
Bug: Clicking on the remove of an Atomic-Object (not univalent) redirects to not found page

### ISSUE THREAD

**Issue by ManondW99** [AmpersandTarski/prototype-frontend#129]
To reproduce the bug, go to any not univalent atomic-object and try to remove the first element. When you click on the first element, it does nothing the first time (that actually should: #128 ), and on the second click it redirects to the 404 not found page (created at issue #74 ).

![Image](https://user-images.githubusercontent.com/25156290/212643428-88353b78-000c-40e3-a02f-3b60fd5a087d.gif)

**Comment by hanjoosten** [comment]
I don't understand what is going on here. That makes it hard to diagnose and 'solve' the bug. I think a bug report should at least mention what you were doing (the context), what happened and what you expected. Now I can only guess. 
I think in general it is a good habit to write these things explicitly in a bug report.

**Comment by Michiel-s** [comment]
Marked done
