### ISSUE TITLE
Atomic-HUGEALPHANUMERIC

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#13]
Should adhere to CRUD permissions for the add/edit page.

This box is supposed to be HUGE!!!

Like this:

![Image](https://user-images.githubusercontent.com/25156290/204808995-52304f21-994a-427c-9f61-ddd897311188.png)

source: https://primefaces.org/primeng/editor

**Comment by Michiel-s** [comment]
I agree. I likes this!
