### ISSUE TITLE
Atomic-Components must adhere to "is total" relations (with respect to is Univalent relations)

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#136]
The Atomic-Component cannot be empty/removed, since there must exist at least one relation.

- [x] In the case of is Univalent (can be at most one), the atomic-component cannot be empty, e.g. a person's name must not be able to be deleted.
- [ ] In the case of is Total (must be at least one), the atomic-component must have at least one element, e.g. a book with no genres cannot exist, there must be at least one genre it corresponds to.

**Comment by hanjoosten** [comment]
@LiWeiYeh : I edited the description. Univalent and Total are restrictions on the cardinality of a relation. The corresponding boolean (isUni resp. isTot) says whether or not such restriction holds for the relation.
