### ISSUE TITLE
Create the import page of the management API

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#143]
The import page should be able to insert files (json) into the application. These files can be used to (re)populate the population. 

![Image](https://user-images.githubusercontent.com/25156290/214006323-3e821cf4-6a9b-46b0-9864-9682e7473633.png)

**Comment by Michiel-s** [comment]
@byTinus we talked about this issue this morning. The screenshot shows the importer in the current implementation.

You can find the importer at route: `/ext/importer`

**Comment by byTinus** [comment]
@Michiel-s Is the file queue necessary? Currently, I've added a file drop zone in which you can select and remove files before uploading, and once you hit upload, they're sent to the API. So the file queue is now embedded into the drop zone, you could say.
![image](https://user-images.githubusercontent.com/58219126/217560218-4afcc9d4-3001-46f0-801d-49f6ab415d45.png)

**Comment by Michiel-s** [comment]
Fine by me.

Please take care about layout and styling.
