### ISSUE TITLE
Atomic-OBJECT

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#15]
Should adhere to CRUD permissions for the add/edit page.

- [x] can create
- [x] can read
- [x] can update
- [x] can delete

**Comment by ManondW99** [comment]
This story is the same as #98

**Comment by Michiel-s** [comment]
For explanation of the indented CRUD-functionality please read this part of the documentation: https://ampersandtarski.github.io/ampersand/the-language-ampersand/services/crud

Although not applicable for Atomic-OBJECTs. the crud functionality for scalar types (i.e. alphanumeric, date, int, etc) has some special things to know. Read about it in the table in this issue: https://github.com/AmpersandTarski/Ampersand/issues/704
