### ISSUE TITLE
Implement strategy to update Angular FormControls with data returned from API

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/prototype-frontend#161]
## Context
The forms we use for Ampersand are different in nature compared with forms in regular frontend application.

In regular forms (e.g. a page where a user can subscribe to a mailing list) or a page where e.g. customer details can be edit, you initiate the form upon opening the page. Then a) the whole form is submitted or b) certain form fields are patched. The state of the form is kept in the frontend and synced to backend. The logic for each specific form is implemented in the page component itself.

For the generated Ampersand interface pages (and corresponding form controls for fields that can be edit) we require a more generic approach. This is due to:
1. The form logic needs to be the same for all interface pages
2. Updates/patches at one place on the form can effect in other places on the same form. This can be because of effects of the exec-engine or because the same relation/expression is used multiple times in the interface. 

## Design options
We have a couple of options, increasing in complexity.

### Option 1: Update component data on **whole** page after a patch

This could be implemented like so:
```ts
export class ProjectEditComponent extends AmpersandInterface<ProjectEditInterface> implements OnInit {
  public data$!: Observable<ProjectEditInterface>;
  
  public override patch<ProjectEditInterface>(
    resource: ObjectBase,
    patches: Array<Patch | PatchValue>,
  ): Observable<PatchResponse<ProjectEditInterface>> {
    return this.http.patch<PatchResponse<ProjectEditInterface>>(resource._path_, patches).pipe(
      tap((x) => {
        // @ts-expect-error
        this.data$ = from([x.content]); // Update component data
      }),
    );
  }
}
```

### Options 2: Update resource object and manually trigger change detection for Angular to update the component
There might be a solution using the [KeyValueDiffers](https://stackoverflow.com/questions/46330070/angular-4-how-to-watch-an-object-for-changes) change detection helper class. This one is also used by Angular internal.

### Options 3: Use of FormGroup.patchValue()
Idea, not validated yet, is to add a FormGroup to the root component and recursively register form
A track by id for form controls is needed for patchValue to work. Not sure yet if this is possible.

## Todo:
- [ ] Document the design choices
- [ ] Update code base

## Relevant reading material:
* https://stackoverflow.com/questions/46330070/angular-4-how-to-watch-an-object-for-changes
* https://blog.mgechev.com/2017/11/14/angular-iterablediffer-keyvaluediffer-custom-differ-track-by-fn-performance/
* https://blog.angular-university.io/how-does-angular-2-change-detection-really-work/

**Comment by LiWeiYeh** [comment]
For Option 1, there is a slight bug AmpersandTarski/prototype#137. This can be avoided visually by not passing in an observable in the `.html` page, but setting the observable in the `.ts` file with the subscribe method:

```
data: ActiveProjectsInterface[];

// somewhere on patch
Patch() {
    this.data$.subscribe(x => data = x);
}
```
