### ISSUE TITLE
Roles menu should stay visible when changing value of a role

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#176]
**Is your feature request related to a problem? Please describe.**
Relates to #147. The roles menu in the navbar should not close when you change the value of a role.

**Describe the solution you'd like**
When clicking on the roles icon in the navbar, it shows the roles and the values (true/false) relating to that role. When changing the role, the menu instantly closes. However, the desired implementation should keep the roles menu open.

**Describe alternatives you've considered**
Doing this was hard, because we're using primeng as a library, in this case specifically the menu. The primeng menu does not have a method to keep it visible. (Although, there is a `visible` field of the menu, we cannot directly call it).

**Additional context**

**Comment by Michiel-s** [comment]
As discussed last Friday during sprint review, this issue/feature is not needed anymore. It's fine to close the menu when a role is (de)activated
