### ISSUE TITLE
Epic: Create Atomic components

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#2]
**Problem**
In order to display different datatypes and input fields, rap uses "Atomic" components. These components were constructed in AngularJS but do not work with the latest version of Angular.

**Solution**
Recreate the "Atomic" components in the latest version of Angular.

**Tasks**
Create the following components:
- [x] #7
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [x] #17
- [x] #98 

- [x] #117 
- [x] #136

**Comment by sheriffBalunywa** [comment]
@LiWeiYeh Which ones are open and which ones are done?
