### ISSUE TITLE
Service Temporarily Unavailable

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/prototype-frontend#243]
# What happened
I have been testing the Project Management application on the old RAP-system that runs on Azure.
I was able to run a number of (approx. 5-10) compile-run cycles. And then, the system blocked and refused to deploy prototypes, whatever I tried.
![afbeelding](https://user-images.githubusercontent.com/275768/236828763-1b8df216-81b6-4e01-af7b-4b6f1e06703b.png)

# What I expected

# Version of ampersand that was used

# Steps I did before getting the bug.

1. I logged in into `https://rap.tarski.nl`.
2. I created a new script containing the project management application. It can be found on https://github.com/AmpersandTarski/ampersand-models/tree/master/ProjectAdministration.
3. Compile  (button: Compile)
4. Generate a prototype  (button: Prototype)
5. run the prototype (navigate to the prototype and try stuff)
I did steps 2-5 a number of times, an then it failed.

**Comment by FrankTeusink** [comment]
Tried to reproduce.
- 13x compile, profile, re-install, play
- lunch break
- 13x compile, profile, (skipped re-install), play

**Comment by FrankTeusink** [comment]
Didn't use the model from GitHub though. Because
- has some trailing tabs in lines 1-10
- Compile and run profile results in Hello World but no main menu items
? issue with including auxiliary files?

Instead, used single .adl provided by Li Wei

**Comment by FrankTeusink** [comment]
Can't reproduce. Will close. On new release we'll do some additional stress testing.
