### ISSUE TITLE
Put separate .md files into a single file

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#246]
# Purpose
To make the documentation accessible by users, we want all items of one larger topic assembled into one .md-file. With that structure, Docusaurus will make a level-2 menu so that readers of the documentation can find their way more easily.

# Problem
Currently, we have too many small .md-files that should be assembled in one file because a reader will consider these to belong to the same topic.

**Comment by hanjoosten** [comment]
@LiWeiYeh: I have enabled documentation generation for the `prototype-frontend` repo. If you modify the documentation in the `documentation` branch, it will be generated within a couple of minutes after you commit. The page will be accessible via the menu at the left:

![image](https://github.com/AmpersandTarski/prototype-frontend/assets/1159672/47bca591-6293-4916-bb06-b851967bf875)

The page that is rendered there is called the-prototype-frontend.md

![image](https://github.com/AmpersandTarski/prototype-frontend/assets/1159672/170e070f-8aab-4545-9a77-ba48bea38f01)

The idea is that everything about the frontend will be placed in this file, with it's own local menu at the right. 
As always, make sure to start with the purpose of that page.
The current page focuses on getting the project-administration app up and running. Keep in mind that that was only the goal to get all the templates for the angular site in place. The purpose of this reference documentation is to help an ampersand modeler to provide his/her application with an effective frontend.

**Comment by hanjoosten** [comment]
Another tip: If you create errors in the markdown (e.g. broken links), the site will not be redeployed. You will find the error is in the log of [the deployment action](https://github.com/AmpersandTarski/AmpersandTarski.github.io/actions).

**Comment by hanjoosten** [comment]
@LiWeiYeh, Unfortunately, for the prototype-frontend, there still are multiple pages. Please move the contents of `docs/interface-components.md` into `docs/reference-material/the-prototype-frontend.md`, and make sure it will become a single readable story, that can be the reference for anybody who will create a prototype frontend application.

Tip: If you do this work in the branch named `documentation`, the site will be deployed in a couple of minutes with each commit, so you can see the result right away.
