### ISSUE TITLE
Box-RAW

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#26]

**Comment by Michiel-s** [comment]
This is the current compiler template for the Box-RAW for the AngularJS implementation.

As you can see, it displays a simple html `<table>` without markup for ampersand `INTERFACE expr BOX <RAW table>` and a simple `<div>` without markup for ampersand `INTERFACE expr BOX <RAW>` (default).

There is no specific component functionality needed, so I propose to **not** create a separate component for this, but simply keep it as a compiler template. The only thing that is needed is the `ngFor` directive as replacement for `ng-repeat`.

```
$if(crudR)$$if(table)$<div>
    <table>
        <tr ng-repeat="resource in requireArray(resource['$name$'])">$subObjects:{subObj|
            <td>
                $subObj.subObjContents$
            </td>}$
        </tr>
    </table>
</div>$else$<div ng-repeat="resource in requireArray(resource['$name$'])">$subObjects:{subObj|
    $subObj.subObjContents$}$
</div>$endif$$else$<span><i>not readable</i></span>$endif$
```
