### ISSUE TITLE
Connect new/edit projects interface

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#42]
Frontend can use backend to edit projects
- box form
- atomic alphanumeric
- atomic bigalphanumeric
- atomic date
- atomic boolean
- atomic object

Note that this page should also adhere to the CRUD permissions

![Image](https://user-images.githubusercontent.com/25156290/205693921-791bbc19-9b86-4bec-a85c-78f4d9eb707c.png)

**Comment by Michiel-s** [comment]
Marked done
