### ISSUE TITLE
Create clean Angular instance

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/prototype-frontend#6]
**Problem**
The developers will all be working on the same project and need a startingpoint.

**Proposed solution**
One developer creates an empty Angular project.

**Tasks**

- [x] Create empty Angular project in prototype-frontend repo
- [x] Add PrimeNG

**Comment by MarkCorazon** [comment]
- Why is the node_modules directory pushed to the root map of the branche? The project cannot be run in the root directory from my end.
- Why is the whole project in a subdirectory named prototype2.0? I thought the content of the directory should be published on the root directory?

I think you have a node_modules directory inside of the prototype2.0 directory?
