### ISSUE TITLE
Page should redirect to 404 when URL is not valid

### ISSUE THREAD

**Issue by LiWeiYeh** [AmpersandTarski/prototype-frontend#74]

**Comment by Michiel-s** [comment]
I would like to have a 404 page.

Both for static not-found routes (no page) and dynamic not-found (no resource).

See attached blog about how to configure in angular routers module.

For the dynamic 404 we should add an additional http interceptor.

https://blogit.create.pt/pedrolopes/2022/05/05/handling-not-found-routes-in-angular/?amp

**Comment by Michiel-s** [comment]
Marked done
