### ISSUE TITLE
Make the toolbox as an interactive way to show the documentation in docusaurus

### ISSUE THREAD

**Issue by MarkCorazon** [AmpersandTarski/prototype-frontend#76]
# Use case
@stefjoosten has seen the toolbox that was created for the project. The toolbox was originally made for the developers, to get an understanding of the functionality that it had to offer. Stef had the idea to make it into an interactive documentation. 

# Description 
It would be great to have this kind of interactive documentation build into docusaurus, or on a different service that can link to docusaurus or vice versa. The existing toolbox is an easy way to learn and see the possibilities that the components and the project has to offer.

**Comment by Michiel-s** [comment]
I'm not sure yet if this makes sen se. Our documentation (with Docusaurus) is a ReactJS project. For the frontend and the components we use Angular. Will this be compatible?

Please mark this as low prio. It's perfectly fine by me to have the documentation and toolbox in the prototype-frontend for now.

**Comment by Michiel-s** [comment]
We can close this one. Textual documentation of the components can be included in our documentation (ampersandtarski.github.io) using the mechanism that is in place. The docs are picked up from the `./docs` folder automatically.

Interactively exploring the functionality of the components can be done using the toolbox in this (prototype-framework) itself.
