### ISSUE TITLE
Bug: Fix 'any' types in atomic object

### ISSUE THREAD

**Issue by PatrickR079** [AmpersandTarski/prototype-frontend#95]

**Comment by PatrickR079** [comment]
Atomic object has 'any' types that need to be changed to its designated type to follow linting rules

**Comment by stefjoosten** [comment]
I would like to see an analysis of this bug and a proposed solution, so we can verify the outcome of this issue.

**Comment by Michiel-s** [comment]
Done. We have linting in place now. Use of _any_ type is warned.
